function [ys_, params, info] = EstimateGermanPop_steadystate2(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(2)=0;
    ys_(4)=0;
    ys_(6)=0;
    ys_(3)=params(10);
    ys_(7)=ys_(3);
    ys_(1)=0;
    ys_(5)=ys_(3)*params(11);
    ys_(8)=ys_(3);
    % Auxiliary equations
ys_(9)=exo_(1);
ys_(10)=exo_(2);
ys_(11)=exo_(3);
    check_=0;
end
